In [1]:
import pandas as pd
data=pd.read_csv("./sum_cluster.csv")
data

     Unnamed: 0      lat       lon  value
0             0  35.9681  128.4651    4.4
1             1  35.9681  128.4751    9.8
2             2  35.9681  128.4851   37.3
3             3  35.9681  128.4951    3.5
4             4  35.9681  128.5051    0.3
..          ...      ...       ...    ...
505         505  35.8081  128.7151    0.7
506         506  35.8081  128.7251   10.8
507         507  35.8081  128.7351  791.4
508         508  35.8081  128.7451  125.3
509         509  35.8081  128.7551  123.4

[510 rows x 4 columns]

In [2]:
import folium
map_osm = folium.Map(location=[35.8796687,128.4266147], zoom_start=13)
#card_data_place.dropna()

for i in range(0,len(data.index)):
    lat1=data.loc[i,'lat']
    lon1=data.loc[i,'lon']
    if data.loc[i,'value']>0:
        print(i,data.loc[i,'value'])
        folium.CircleMarker([lat1,lon1],radius=data.loc[i,'value']/10000,popup=data.loc[i,'value'],color='red',fill=True).add_to(map_osm)
map_osm.save('sum_cluster.html')

0 4.4
1 9.8
2 37.3
3 3.5
4 0.3
6 0.7
7 1.4
8 233.4
9 7919.46
10 22.5
11 33.3
12 32.0
13 2.7
14 0.7
16 181.1
17 0.3
18 0.7
19 10.9
20 18.9
21 38.1
22 1.7
23 184.9
24 291.5
25 51.0
26 24.8
27 330.3
28 7.999999999999999
30 4.199999999999998
31 41.2
32 67.7
33 6.4
34 2.1
36 7.399999999999999
37 10.6
38 9216.9
39 5287.17
40 13995.1
41 4709.5
42 2.3999999999999995
44 12.2
45 1.6
46 52.1
47 0.7
48 31.4
49 63.0
50 333.4
51 542.8
52 2539.2
53 94.0
54 172.4
55 4.499999999999999
56 1.4
58 1.0
59 0.3
60 6.9
62 10.7
63 1.6
64 4.6
65 0.3
66 9.3
67 7475.0
68 31466.7
69 144373.52
70 28819.0
71 2059.8
72 35.1
73 6.8
74 42.5
75 502.8
76 96.2
77 11926.5
78 4458.4
82 0.7
83 0.7
86 0.7
90 18.9
91 4.0
92 12.4
93 0.7
94 7.1
95 40.4
96 40.0
97 17539.1
98 80150.81999999999
99 59798.8
100 4761.8
101 0.7
102 46.6
103 1900.0
104 47.4
105 2.7
106 90.1
107 5212.2
108 21.5
109 0.3
110 16.3
111 12.0
112 53.9
113 2.8
114 4.9
121 5.999999999999999
122 14.8
123 0.7
124 2.0
125 30.7
126 1.9
127 15516.3
128 109684.73
129 3027.8
130 0.6
131 0.7
132 254.6
133 36954.9
134 197.7
135 1.7
136 32.8
137 70377.9
138 40.49999999999999
139 119.4
140 5.1
149 1.7
150 0.7
151 2.8
152 19.2
153 27.5
154 16.9
155 9.7
156 6.699999999999998
157 10654.6
158 33401.8
159 154.2
160 31.8
161 2927.8
162 73.89999999999998
163 19001.2
164 8791.1
165 9663.4
166 6527.4
167 30516.0
168 1201.6999999999996
169 81.69999999999997
170 3.3
175 124.0
178 0.3
179 0.7
181 0.7
182 18.5
183 11.0
184 10376.0
185 1581.5
186 19.5
187 12396.0
188 28886.75
189 11769.0
190 381.0
191 8450.5
192 10622.5
193 24769.0
194 99540.5
195 85614.0
196 7420.0
197 43126.5
198 2.0
200 604.5999999999998
201 112.3
202 56.1
204 13.999999999999998
205 3.5
210 71.19999999999997
211 15.9
212 1.5
213 19.0
214 5318.5
215 8993.5
216 79.6
217 1689.7
218 36249.84
219 46241.3
220 77695.39
221 17783.3
222 65272.3
223 35492.4
224 179809.3
225 145424.5
226 8209.5
227 40954.5
228 17891.699999999993
229 24.6
230 312.2999999999999
231 222.5
232 8.899999999999997
233 49.6
234 140.7
235 434.19999999999993
239 0.7
240 105.1
241 163.39999999999995
242 33.0
243 909.5
244 13.5
245 4.5
246 1993.8
247 2632.1
248 7532.2
249 95257.6
250 108507.64
251 87055.53
252 97782.7
253 92274.3
254 116304.9
255 86903.6
256 506082.2
257 147459.05
258 82036.81
259 64903.14
260 80606.45999999999
261 540.0
262 676.2
263 223.9
264 6922.0
265 6426.2
266 4508.7
267 348.2
268 891.8
269 13.6
270 4016.6
271 18919.1
272 4064.5
273 26545.0
275 8.0
276 770.4
277 7960.4
278 86038.8
279 98299.3
280 115096.2
281 122019.23
282 613341.62
283 546151.5
284 118075.21
285 80476.37
286 244701.5
287 84146.5
288 25064.0
289 12538.4
290 25216.6
291 49796.8
292 91420.16
293 15662.0
294 29261.5
295 15431.2
296 143981.24
297 1187.1
298 6473.799999999998
299 115.9
300 3400.4
301 2.3999999999999995
302 31706.0
303 12961.0
304 20994.5
305 27208.0
306 37998.7
307 16214.4
308 53638.0
309 159450.34999999998
310 110165.37
311 99740.66
312 687242.7
313 327406.65
314 125649.32
315 123958.3
316 211062.55
317 198304.6
318 32025.4
319 7.3
320 157.5
321 168.1
322 14754.9
323 76972.71
324 52423.89
325 82649.96999999999
326 5214.2
327 63.3
328 1.0
330 17719.5
331 96794.84
332 233526.1
333 78034.5
334 165308.6
335 78778.1
336 181198.65
337 101871.09
338 275505.07
339 199203.12
340 66296.5
341 110966.87
342 218919.6
343 51287.95
344 79177.44
345 96376.18
346 64691.5
347 84680.5
348 146596.26
349 8513.6
350 586.3
351 166.89999999999995
352 62.49999999999999
353 12.2
354 20.8
355 214.0
356 5.5
357 17.5
358 0.7
359 14.3
360 792.1999999999998
361 1873.5
362 36468.0
363 643.0
364 6333.5
365 2468.0
366 58024.3
367 103485.8
368 36000.2
369 77624.5
370 212271.48
371 141840.88999999998
372 136524.90999999995
373 85717.0
374 54875.9
375 110434.99
376 61879.55
377 33208.0
378 948.8
379 5.799999999999999
380 17163.129999999994
381 19182.49
382 17919.8
383 107765.72
384 101370.2
385 2471.4
386 495.9
387 11.4
388 1229.4999999999998
389 1717.8
391 52.7
392 10402.5
393 5790.0
394 17372.5
395 6408.5
396 62207.6
397 49242.5
398 113972.17
399 217380.52
400 17444.2
401 15621.8
402 10292.0
403 27119.4
404 37859.3
405 113782.78
406 18193.0
407 1359.0
408 16.299999999999994
409 1.0
410 565.2
411 7487.1
412 6910.8
413 6389.799999999998
414 55395.7
415 76856.70999999999
416 59150.17999999999
417 36279.37
418 106175.06
419 74.99999999999999
420 13.2
422 75.0
423 2467.5
424 7054.5
425 25614.5
426 89128.0
427 244277.85
428 86248.25
429 932.0
430 15.0
431 0.5
432 16.5
433 2.0
434 23188.0
435 32059.0
436 70426.15
437 150365.35
438 23904.22
439 34.599999999999994
440 8.8
441 43.5
442 21.7
443 1.7
444 477.9
445 2252.8
446 2349.5
447 964.7
448 542.9
449 176.5
450 52.4
451 620.0
452 301.0
453 4521.0
454 166175.8
455 165429.35
456 90251.8
457 168936.5
458 40390.5
459 427.5
460 2.0
461 0.5
462 1.0
463 1.5
464 1955.5
465 15020.0
466 41.0
467 3545.0
468 13370.7
469 8.7
473 0.7
474 1.4
475 120.6
476 1182.8
477 512.4
478 483.3
479 716.9
480 9.0
481 45.4
482 77616.01000000001
483 92984.1
484 13148.5
485 22990.4
486 26761.3
487 36166.9
488 10344.2
489 2733.7
490 1.0
493 0.3
494 6.5
495 12514.8
496 7.999999999999999
499 0.7
500 7.199999999999998
502 1.0
503 3.8
505 0.7
506 10.8
507 791.4
508 125.29999999999998
509 123.4